import Head from 'next/head'
import { Inter } from '@next/font/google'
import Image from 'next/image';
import Link from 'next/link';
 
const inter = Inter({ subsets: ['latin'] })

export default function Home({data}) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>

        <nav>

          <Link href="/" passHref>
            Home
          </Link>

          <Link href="/about-us" passHref>
          About us
          </Link>

          <Link href="/events" passHref >
            Events
          </Link>

        </nav>

      </header>


     <main>

      {data.map(ev=>
      <Link key={ev.id} href={`/events/${ev.id}`} passHref>
      
        <Image height={100} width={200} alt={`${ev.title}`} src={`${ev.image}`}/>
        <h2>{`${ev.title}`}</h2>
        <p>{`${ev.description}`}</p>
      </Link>
      )}

      </main>
    </>
  )
}

export async function getServerSideProps(){

  const {events_categories} = await import('../data/data.json');
  console.log(events_categories)
 
  return { 
    props:{ 
      data:events_categories
    }
  };

}
